server:
  port: 9999

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.48.1.253:1521:ora11g
      username: zjallinpaytest
      password: zjallinpaytest
      ##初始化连接池时创建的连接数，默认0##
      initial-size: 5
      ##连接池最小连接数，无默认值##
      min-idle: 5
      ##连接池最大连接数，默认8##
      max-active: 20
      ##获取连接时的最大等待时间##
      max-wait: 5000
      ##申请连接时执行validationQuery检测连接是否有效，默认开启##
      test-on-borrow: false
      ##归还连接时执行validationQuery检测连接是否有效，默认开启##
      test-on-return: false
      ##空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效##
      test-while-idle: true
      time-between-eviction-runs-millis: 90000
      validation-query: SELECT 1 FROM DUAL
      ##保持空闲的最?长时间##
      min-evictable-idle-time-millis: 600000
      filter: stat,wall,log4j,config


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hx.hxtspro.entity

logging:
  config: classpath:log4j2.xml
  level:
    com.hx.hxtspro.dao: debug

